# Generated by Django 4.2.3 on 2023-07-15 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imdbuser',
            name='my_watchlist',
            field=models.ForeignKey(default=None, null='True', on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to='games.videogame'),
            preserve_default='True',
        ),
    ]
