# Generated by Django 4.2.3 on 2023-07-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_imdbuser_my_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imdbuser',
            name='my_rating',
        ),
        migrations.RemoveField(
            model_name='imdbuser',
            name='my_review',
        ),
        migrations.RemoveField(
            model_name='imdbuser',
            name='my_watchlist',
        ),
    ]
