# Generated by Django 4.2.3 on 2023-07-19 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogame',
            name='soundtrack',
        ),
        migrations.CreateModel(
            name='SoundTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soundtracks', models.FileField(default=None, null=True, upload_to='soundtracks/')),
                ('game', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soundtracks', to='games.videogame')),
            ],
        ),
    ]
