# Generated by Django 4.2.3 on 2023-07-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_videogame_review_review_game_review_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogame',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='frequent_questions',
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='goof',
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='parents_guide',
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='picks',
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='trivia',
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='video',
        ),
        migrations.AlterField(
            model_name='videogame',
            name='director',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='writer',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
