# Generated by Django 4.2.3 on 2023-07-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_rating_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogame',
            name='imdb_rating',
        ),
    ]
