# Generated by Django 4.2.3 on 2023-07-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_videogame_imdb_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='imdb_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, editable=False, max_digits=6, null=True),
        ),
    ]
