# Generated by Django 4.2.3 on 2023-07-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_videogame_cast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='award',
            field=models.CharField(default=None, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='box_office',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='color',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='company',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='country_of_origin',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='crazy_credits',
            field=models.CharField(default=None, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='director',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='genre',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='language',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='nickname',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='soundmix',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='soundtrack',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='storyline',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='title',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='writer',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
