# Generated by Django 4.2.3 on 2023-07-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_review_review_alter_videogame_award_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='certificate',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
