# Generated by Django 4.2.3 on 2023-07-16 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_videogame_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogame',
            name='runtime',
        ),
    ]
