# Generated by Django 4.2.3 on 2023-07-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_rating_watchlist_remove_mywatchlist_game_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_information', models.CharField(default=None, max_length=1000, null=True)),
                ('track_games', models.CharField(default=None, max_length=1000, null=True)),
                ('discover', models.CharField(default=None, max_length=1000, null=True)),
                ('featured_content', models.CharField(default=None, max_length=1000, null=True)),
                ('common_issues', models.CharField(default=None, max_length=1000, null=True)),
                ('special_events', models.CharField(default=None, max_length=1000, null=True)),
                ('new_features', models.CharField(default=None, max_length=1000, null=True)),
                ('mobile_web', models.CharField(default=None, max_length=1000, null=True)),
            ],
        ),
    ]
