# Generated by Django 4.2.3 on 2023-07-17 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_help'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='my_rating',
            new_name='your_rating',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='is_watched',
            new_name='your_watchlist',
        ),
    ]
